/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a458f445-d252-4547-99b7-648ec4d34794",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CGbit3nwz",
    "aws_user_pools_web_client_id": "7pq4dlle04v8s0t7d75lb8ogso",
    "oauth": {}
};


export default awsmobile;
